title: Highly Unlikely
author: Tobias Pielok
email: tpielok@gmail.com
theme: minimal
description: > # this means to ignore newlines until "baseurl:"
  Blog about probabilistic machine learning



# social links
twitter_username: tpielok1
github_username:  tpielok
show_excerpts: true # set to false to remove excerpts on the homepage
